# Generated by Django 2.2.5 on 2019-10-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20191021_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='messages',
        ),
        migrations.AddField(
            model_name='discussion',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.Message'),
        ),
    ]
