# Generated by Django 2.2.5 on 2019-10-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20191021_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='messaging.Discussion'),
        ),
    ]
