# Generated by Django 2.2.5 on 2019-10-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20191021_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.Discussion'),
        ),
    ]
