# Generated by Django 2.2.5 on 2019-11-01 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20191021_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
