# Generated by Django 2.2.5 on 2019-11-02 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0007_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notification_msg',
        ),
    ]
