# Generated by Django 2.2.5 on 2019-11-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_auto_20191102_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_msg',
            old_name='notification_msg',
            new_name='notification_msgs',
        ),
    ]
