# Generated by Django 2.2.5 on 2019-11-02 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_auto_20191102_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_msg',
            name='notification_msgs',
        ),
        migrations.AddField(
            model_name='notification_msg',
            name='notification_disc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Discussion'),
        ),
    ]
