# Generated by Django 2.2.5 on 2019-11-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20191102_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_msg',
            old_name='notification_read',
            new_name='notification_unread',
        ),
    ]
