# Generated by Django 2.2.5 on 2019-11-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_auto_20191102_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notification_msg',
        ),
    ]
