# Generated by Django 2.2.5 on 2019-11-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_auto_20191102_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_read',
            new_name='notif_read',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_user',
            new_name='notif_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_chat',
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_discussion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
