# Generated by Django 2.2.5 on 2019-12-27 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0015_auto_20191117_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='pariticipants',
            field=models.ManyToManyField(related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
