# Generated by Django 2.2.5 on 2020-01-02 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0017_notification2'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification2',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_not', to=settings.AUTH_USER_MODEL),
        ),
    ]
