# Generated by Django 2.2.5 on 2020-01-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0018_notification2_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification2',
            name='sender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
