# Generated by Django 2.2.5 on 2020-01-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0019_auto_20200102_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification2',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
    ]
