# Generated by Django 2.2.5 on 2020-01-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0020_notification2_is_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
