# Generated by Django 2.2.5 on 2019-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Conference name', max_length=250, null=True, verbose_name='Conference name')),
                ('website', models.URLField(default='Conference.com', null=True, verbose_name='website')),
            ],
        ),
    ]
