# Generated by Django 2.2.5 on 2019-12-30 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recoms', '0011_auto_20191226_2023'),
        ('Conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'permissions': (('CED_sessions', 'Create, Edite & Delete sessions'), ('edit_session', 'Edite specific session'), ('W2vec_training', 'W2vec training'), ('Send_invitations', 'Send invitations'), ('give_rights', 'Give rights to users'), ('send_msg', 'Send msgs to all conf users'), ('set_sessions_status', 'set session as ongoing, finished or not yet started by chairman'))},
        ),
        migrations.AddField(
            model_name='conference',
            name='chairs',
            field=models.ManyToManyField(related_name='chair_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizers',
            field=models.ManyToManyField(related_name='organizer_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='speakers',
            field=models.ManyToManyField(related_name='speaker_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='superusers',
            field=models.ManyToManyField(related_name='superuser_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='themes',
            field=models.ManyToManyField(related_name='conferences', to='recoms.Theme'),
        ),
        migrations.AddField(
            model_name='conference',
            name='users',
            field=models.ManyToManyField(related_name='conferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
