# Generated by Django 2.2.5 on 2019-12-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='Finish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='Start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
