# Generated by Django 2.2.5 on 2019-12-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0002_auto_20191230_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='chairs',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='organizers',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='superusers',
        ),
    ]
