# Generated by Django 2.2.5 on 2019-12-29 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recoms', '0011_auto_20191226_2023'),
        ('Conference', '0002_auto_20191228_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'permissions': (('CED_sessions', 'Create, Edite & Delete sessions'), ('edit_session', 'Edite specific session'), ('W2vec_training', 'W2vec training'), ('Send_invitations', 'Send invitations'), ('give_rights', 'Give rights to users'), ('send_msg', 'Send msgs to all conf users'), ('set_sessions_status', 'set session as ongoing, finished or not yet started by chairman'))},
        ),
        migrations.AddField(
            model_name='conference',
            name='Themes',
            field=models.ManyToManyField(related_name='conferences', to='recoms.Theme'),
        ),
        migrations.AddField(
            model_name='conference',
            name='Users',
            field=models.ManyToManyField(related_name='conferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
