# Generated by Django 2.2.5 on 2019-12-30 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Conference', '0006_conference_organizers'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='speakers',
            field=models.ManyToManyField(related_name='speaker_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
