# Generated by Django 2.2.5 on 2019-10-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique='True', verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Student', 'Student'), ('Researcher', 'Researcher'), ('Engineer', 'Engineer'), ('Commercial', 'Commercial'), ('Other', 'Other')], max_length=20, verbose_name='Status')),
                ('webpage', models.CharField(default='LinkedIn, Researchgate, blog..', max_length=50, verbose_name='Webpage')),
                ('organism', models.CharField(default='University/Institute/Company..', max_length=50, verbose_name='Organism')),
                ('key_words', models.CharField(default='Keywords', max_length=50, verbose_name='Key words')),
                ('first_name', models.CharField(default='', max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=20, verbose_name='Last name')),
                ('is_chair', models.BooleanField(default=False, verbose_name='Chair')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Organizer')),
                ('is_presenting', models.BooleanField(default=False, verbose_name='Presenting')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='Sex')),
                ('country', models.CharField(default='Country', max_length=20, verbose_name='Country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
