# Generated by Django 2.2.5 on 2019-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key_words',
            field=models.CharField(default='Keywords', max_length=250, verbose_name='Key words'),
        ),
    ]
