# Generated by Django 2.2.5 on 2019-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0001_initial'),
        ('Account', '0002_auto_20191201_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Conference',
            field=models.ManyToManyField(related_name='conferences', to='Conference.Conference'),
        ),
    ]
