# Generated by Django 2.2.5 on 2019-12-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_account_conference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': {('in_this_conference', 'if user is accepted in conference')}},
        ),
        migrations.RemoveField(
            model_name='account',
            name='Conference',
        ),
    ]
