# Generated by Django 2.2.5 on 2019-11-30 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=50, verbose_name='title')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(related_name='session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
