# Generated by Django 2.2.5 on 2019-11-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='authors',
        ),
        migrations.AddField(
            model_name='session',
            name='authors',
            field=models.CharField(default='authors', max_length=50, verbose_name='authors'),
        ),
    ]
