# Generated by Django 2.2.5 on 2019-12-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recoms', '0002_auto_20191130_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(default='room', max_length=50, verbose_name='room')),
                ('title', models.CharField(default='title', max_length=50, verbose_name='title')),
            ],
        ),
        migrations.RenameField(
            model_name='session',
            old_name='authors',
            new_name='Authors',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='session',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='session',
            name='Abstract',
            field=models.CharField(default='title', max_length=300, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='session',
            name='Final_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='Room',
            field=models.CharField(default='room', max_length=50, verbose_name='room'),
        ),
        migrations.AddField(
            model_name='session',
            name='Speakers',
            field=models.CharField(default='authors', max_length=50, verbose_name='authors'),
        ),
        migrations.AddField(
            model_name='session',
            name='Start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='Status',
            field=models.CharField(choices=[('Not yet', 'Not yet'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='session',
            name='Theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='recoms.Theme'),
        ),
    ]
