# Generated by Django 2.2.5 on 2019-12-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoms', '0003_auto_20191223_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='Final_timeC',
            field=models.CharField(max_length=20, null=True, verbose_name='Final time'),
        ),
        migrations.AddField(
            model_name='session',
            name='Start_timeC',
            field=models.CharField(max_length=20, null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='session',
            name='Abstract',
            field=models.CharField(default='abstract', max_length=300, verbose_name='title'),
        ),
    ]
