# Generated by Django 2.2.5 on 2019-12-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoms', '0004_auto_20191224_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='Recommended',
            field=models.BooleanField(default=False),
        ),
    ]
