# Generated by Django 2.2.5 on 2019-12-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoms', '0005_session_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='on_time',
            field=models.BooleanField(default=False),
        ),
    ]
