# Generated by Django 2.2.5 on 2019-12-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoms', '0008_session_reminded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='Reminded',
        ),
    ]
