# Generated by Django 2.2.5 on 2019-12-26 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoms', '0010_session_reminded_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='Reminded_users',
            field=models.ManyToManyField(related_name='reminded_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
