# Generated by Django 2.2.5 on 2020-01-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoms', '0011_auto_20191226_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='topic',
            field=models.CharField(default='topic', max_length=50, verbose_name='Topic'),
        ),
    ]
