# Generated by Django 2.2.5 on 2020-01-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recoms', '0012_theme_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='topic',
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=50, verbose_name='title')),
                ('Theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='recoms.Theme')),
            ],
        ),
    ]
