# Generated by Django 2.2.5 on 2020-01-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoms', '0013_auto_20200118_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='exists',
            field=models.BooleanField(default=False),
        ),
    ]
